### PR TITLE
Update README.md to include a list of issues addressed by idasix

### PR DESCRIPTION
**Pull request by nirizr**

### CODE REVIEW

**Comment by shiftre** [comment]
maybe i'm being silly here, but why not reference to the project itself ? 

"As IDA moves on to newer versions (starting from 6.9 to 6.95 and soforth), idasix tries to assure compatibility along with those versions. There are already a few them there which resolve 6.9 and 6.95 issues."

**Comment by nirizr** [comment]
You mean rematch? Adding a list of projects using it?

**Comment by shiftre** [comment]
Yup.
I got confused, I thought you made REmatch README that.
But yeah, "projects using idasix" is nice

**Comment by nirizr** [comment]
👍 Sounds good. Do you wanna add that?

**Comment by shiftre** [comment]
With great honor.

**Pull request merged**
